version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=conthabil_db
      - POSTGRES_USER=conthabil_user
      - POSTGRES_PASSWORD=strongpassword123
    ports:
      - "5432:5432"

  api:
    container_name: django_api
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/:/app/
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=conthabil_db
      - DB_USER=conthabil_user
      - DB_PASS=strongpassword123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: