# Generated by Django 5.2.5 on 2025-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='competence',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
